START C:\Windows\System32\tscon.exe 0 /dest:console
START C:\Windows\System32\tscon.exe 1 /dest:console
START C:\Windows\System32\tscon.exe 2 /dest:console
START C:\Windows\System32\tscon.exe 2 /dest:console
START C:\Windows\System32\tscon.exe 3 /dest:console
START C:\Windows\System32\tscon.exe 4 /dest:console
START C:\Windows\System32\tscon.exe 5 /dest:console
START C:\Windows\System32\tscon.exe 6 /dest:console
START C:\Windows\System32\tscon.exe 7 /dest:console
START C:\Windows\System32\tscon.exe 8 /dest:console
START C:\Windows\System32\tscon.exe 9 /dest:console
START C:\Windows\System32\tscon.exe 10 /dest:console
START C:\Windows\System32\tscon.exe 11 /dest:console
START C:\Windows\System32\tscon.exe 12 /dest:console
START C:\Windows\System32\tscon.exe 13 /dest:console